name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bats testing framework
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Run tests
        working-directory: ./test
        run: |
          bats npm-proxy-test.bats
